name: The_DT_Plugin
version: '0.1'
main: org.thedt.the_dt_plugin.The_DT_Plugin
api-version: '1.20'
commands:
  htp:
    description: Teleport to where you spawned
    usage: "/htp"
  spawn:
    description: Teleport to world spawn
    usage: "/spawn"